# Generated by Django 5.1.7 on 2025-03-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_phone', models.CharField(max_length=15, unique=True)),
                ('user_password', models.CharField(max_length=128)),
                ('remember_me_token', models.CharField(blank=True, max_length=255, null=True)),
                ('password_reset_token', models.CharField(blank=True, max_length=255, null=True)),
                ('password_reset_expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
